version: "3.8"

services:
    scala-study:
        container_name: scala-study 
        build: .
        volumes: 
          - type: bind
            source: ../volume
            target: /code
        command: "tail -f /dev/null"


